extraction:
  java:
    index:
      build_command: "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && export\
        \ JAVACMD=$JAVA_HOME/bin/java && mvn verify -X -e"
      xml_mode: "default"
      java_version: "11"
