
version: "3"
services:
  database:
    image: postgres:11.1
    container_name: database
    ports:
      - "5437:5432"
    volumes:
      - ../database:/docker-entrypoint-initdb.d/database
      - ../database/create_database.sh:/docker-entrypoint-initdb.d/create_database.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8087:80"
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=semillas@atixlabs.com
      - PGADMIN_DEFAULT_PASSWORD=semillas

